#pragma once

#include <map>
#include <string>

#include "Opcodes.hpp"

static const std::map<Opcodes, std::string> Mnemonic_t = {
    std::make_pair(Opcodes::NOP, "NOP"),
    std::make_pair(Opcodes::LDI, "LDI"),
    std::make_pair(Opcodes::LDA, "LDA"),
    std::make_pair(Opcodes::LDR, "LDR"),
    std::make_pair(Opcodes::STI, "STI"),
    std::make_pair(Opcodes::STA, "STA"),
    std::make_pair(Opcodes::STR, "STR"),
    std::make_pair(Opcodes::SHL, "SHL"),
    std::make_pair(Opcodes::SHR, "SHR"),
    std::make_pair(Opcodes::AND, "AND"),
    std::make_pair(Opcodes::BOR, "BOR"),
    std::make_pair(Opcodes::XOR, "XOR"),
    std::make_pair(Opcodes::NOT, "NOT"),
    std::make_pair(Opcodes::PSA, "PSA"),
    std::make_pair(Opcodes::PSI, "PSI"),
    std::make_pair(Opcodes::PSR, "PSR"),
    std::make_pair(Opcodes::POP, "POP"),
    std::make_pair(Opcodes::INC, "INC"),
    std::make_pair(Opcodes::DEC, "DEC"),
    std::make_pair(Opcodes::ADI, "ADI"),
    std::make_pair(Opcodes::ADA, "ADA"),
    std::make_pair(Opcodes::ADR, "ADR"),
    std::make_pair(Opcodes::SUI, "SUI"),
    std::make_pair(Opcodes::SUA, "SUA"),
    std::make_pair(Opcodes::SUR, "SUR"),
    std::make_pair(Opcodes::MUI, "MUI"),
    std::make_pair(Opcodes::MUA, "MUA"),
    std::make_pair(Opcodes::MUR, "MUR"),
    std::make_pair(Opcodes::DIV, "DIV"),
    std::make_pair(Opcodes::DIA, "DIA"),
    std::make_pair(Opcodes::DIR, "DIR"),
    std::make_pair(Opcodes::MOI, "MOI"),
    std::make_pair(Opcodes::MOA, "MOA"),
    std::make_pair(Opcodes::MOR, "MOR"),
    std::make_pair(Opcodes::CMI, "CMI"),
    std::make_pair(Opcodes::CMA, "CMA"),
    std::make_pair(Opcodes::CMR, "CMR"),
    std::make_pair(Opcodes::JMP, "JMP"),
    std::make_pair(Opcodes::JEQ, "JEQ"),
    std::make_pair(Opcodes::JNQ, "JNQ"),
    std::make_pair(Opcodes::JMC, "JMC"),
    std::make_pair(Opcodes::JNC, "JNC"),
    std::make_pair(Opcodes::JMO, "JMO"),
    std::make_pair(Opcodes::JNO, "JNO"),
    std::make_pair(Opcodes::JSR, "JSR"),
    std::make_pair(Opcodes::RTS, "RTS"),
    std::make_pair(Opcodes::OUT, "OUT"),
    std::make_pair(Opcodes::HLT, "HLT"),
};
